### ISSUE TITLE
Does not affect gameplay at all on new worlds in latest versions

### ISSUE THREAD

**Issue by colelawrence** [Di3mex/ExtraHardMode#16]
I can not seem to understand why it does not affect my gameplay.
Does not work for me on versions 1.6.4R2.0 (Using old plugin version) or 1.7.2-R0.3 (Using latest EHM)

_/server.properties_

``` yaml
#Minecraft server properties
#Thu May 01 06:26:46 MSD 2014
generator-settings=
op-permission-level=4
allow-nether=true
level-name=world
enable-query=false
allow-flight=false
announce-player-achievements=true
server-port=25565
level-type=DEFAULT
enable-rcon=false
force-gamemode=false
level-seed=hoya
server-ip=
max-build-height=127
spawn-npcs=true
white-list=false
spawn-animals=true
texture-pack=
snooper-enabled=true
hardcore=false
online-mode=true
resource-pack=
pvp=true
difficulty=1
enable-command-block=false
player-idle-timeout=0
gamemode=0
max-players=4
spawn-monsters=true
view-distance=10
generate-structures=true
spawn-protection=16
motd=Exter Herd Mude
```

_/plugins/ExtraHardMode/config.yml_

``` yaml
ExtraHardMode:
  Config Type: MAIN
  Enabled Worlds:
  - world
  Bypassing:
    Check For Permission: true
    Creative Mode Bypasses: true
    Operators Bypass: false
  World Rules:
    Mining:
```

**Note defaults are retained for rest of config.yml file**

This plugin has worked wonderfully in the past so it may be a set-up issue that I cannot find in the manual.

Thanks!
